  - name: Copy the standrd index.html file 
    copy: src=index.html dest=/var/www/html/index.html mode=0644

  - name: Updating iptable rules
    command: /sbin/iptables -I INPUT 1 -p tcp --dport http -j ACCEPT

  - name: Save iptable rule
    command: iptables-save

  - name: Start httpd service
    service: name=httpd state=started
 
